/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOptions {
  mode: string
  filename: string
}

export interface TransformResult {
  code: string
}

export declare function transform(sourceText: string, options: TransformOptions): TransformResult
